hugowatch:
  image: jojomi/hugo:latest
  volumes:
    - ./src:/src
    - ./public:/output
  environment:
    - HUGO_WATCH=1
  ports:
    - 1313:1313

hugobuild:
  image: jojomi/hugo:latest
  volumes:
    - ./:/src
    - ./public:/output
