[[redirects]]
  from = "https://www.f-online.at/*"
  to = "https://www.f-online.app/at/:splat"
  status = 301
  force = true
  query = {path = ":path"}

[build]
  command = "npm install && npm run build"
  publish = "public"
  base = ""
  environment = { NODE_VERSION = "16" }
 
[[plugins]]
  package = "@netlify/plugin-gatsby"
