languageCode = "de-AT"
title = "F-Online"
disableKinds = ["taxonomy", "taxonomyTerm"]
baseURL = "https://www.f-online.at"

[permalinks]
  posts = "/:slug/"

[markup.goldmark.renderer]
  unsafe= true

[params]
  fonlineDateCheck = "22.02.2021"
  fonlineDateUpdate = "20.08.2020"
