languageCode = "de-AT"
title = "F-Online"
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  posts = "/:slug/"

[markup.goldmark.renderer]
  unsafe= true

[params]
  fonlineDateCheck = "08.12.2019"
  fonlineDateUpdate = "01.09.2019"
