[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.60.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.60.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.60.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.60.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/news/*"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschulen/burgenland"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschulen/kaernten"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschulen/niederoesterreich"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschulen/oberoesterreich"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschulen/salzburg"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschulen/steiermark"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschulen/tirol"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschulen/vorarlberg"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschulen/wien"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/fahrschule/*"
  to = "/fahrschulen"
  status = 301
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
